# Generated by Django 5.0.1 on 2024-07-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='until_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отмены тарифа'),
        ),
    ]
