version: '3.8'

services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/django_static

  server:
    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/server-entrypoint.sh
    volumes:
      - static_volume:/app/backend/django_static
      - ./backend:/app/backend
    expose:
      - 8000
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/worker-entrypoint.sh
    volumes:
      - static_volume:/app/backend/django_static
      - ./backend:/app/backend
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
    env_file:
      - .env
    depends_on:
      - server
      - redis

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
      - 6379

  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

volumes:
  static_volume: {}
  postgres_data: {}
