# Generated by Django 5.0.1 on 2024-07-26 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер квартиры')),
                ('square', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Площадь квартиры')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('bld_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер корпуса')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, unique=True, verbose_name='№ счётчика')),
            ],
        ),
        migrations.CreateModel(
            name='CounterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Показания')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2024)], verbose_name='Год')),
            ],
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('street', 'house_number', 'bld_number'), name='unique_address'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.CheckConstraint(check=models.Q(('house_number__gt', 0)), name='house_number_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.CheckConstraint(check=models.Q(('bld_number__range', (1, 20))), name='bld_number_gte_1_lte_20'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartments.building', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='counter',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='counters', to='apartments.apartment', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='countervalue',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='apartments.counter', verbose_name='№ счётчика'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('month', 'year'), name='unique_month_year'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(check=models.Q(('month__range', (1, 12))), name='month_gte_1_gle_12'),
        ),
        migrations.AddField(
            model_name='countervalue',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='counters', to='apartments.period', verbose_name='Период'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(check=models.Q(('square__gt', 0)), name='square_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_apartment_for_building'),
        ),
    ]
