# Generated by Django 5.0.1 on 2024-07-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_apartment_for_building'),
        ),
    ]
